version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/Financial-Times/concept-ingester
    environment: 
      CIRCLE_TEST_REPORTS: /tmp/test-reports
      CIRCLE_ARTIFACTS: /tmp/artifacts
  
    steps: 
      - checkout
      - run: 
          name: Create folders
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS/golang
            mkdir -p $CIRCLE_ARTIFACTS
      - run: 
          name: Download dependancies
          command: |
            go get -u github.com/golang/dep/cmd/dep
            go get -u github.com/jstemmer/go-junit-report
            go get -u github.com/mattn/goveralls
      - run: 
          name: Download vendored dependancies
          command: |
            dep ensure
      - run: 
          name: Build app
          command: |
            go build -v
      - run: 
          name: Run tests and create coverage report
          command: |
            go test -race -cover -coverprofile=$CIRCLE_ARTIFACTS/coverage.out | go-junit-report > $CIRCLE_TEST_REPORTS/golang/junit.xml
      - run: 
          name: Upload coverage report
          command: |
            goveralls -coverprofile=$CIRCLE_ARTIFACTS/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - store_test_results:
          path: /tmp/test-reports
      - store_artifacts:
          path: /tmp/artifacts
          destination: build